#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential' 
cookbook 'mysql'
cookbook 'git', git: 'https://github.com/fnichol/chef-git.git'

# cookbook 'chef-client'
# cookbook 'apache2', '>= 1.0.0'

